spring.application.name=aircraft-service

#DataSource Properties
spring.datasource.url = jdbc:mysql://localhost:3306/aircraft_mro_db
spring.datasource.username=root
spring.datasource.password=12345

spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

#ddl-auto should be initialized to 'update' to automatically create/update the database schema based on the JPA entities
spring.jpa.hibernate.ddl-auto=update
# Set the above property to 'validate' in production to ensure that the database schema matches the JPA entities without making any changes
#spring.auto.hibernate.ddl-auto = validate

# Makes easy for Postman Testing by disables spring's default security for rest end points and actuators.
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
  org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration